package com.josefrias.air_quality;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.containsString;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class WebInterfaceTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void interface_test() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1299, 713));
    driver.findElement(By.id("lat")).click();
    driver.findElement(By.id("lat")).clear();
    driver.findElement(By.id("lon")).clear();
    driver.findElement(By.id("lat")).sendKeys("40.64427");
    driver.findElement(By.id("lon")).click();
    driver.findElement(By.id("lon")).click();
    {
      WebElement element = driver.findElement(By.id("lon"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("lon")).click();
    driver.findElement(By.id("lon")).click();
    driver.findElement(By.id("lon")).sendKeys("-8.64554");
    driver.findElement(By.cssSelector(".fa")).click();
    driver.findElement(By.cssSelector("h1")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Air Quality for lat 40.64427 and lon -8.64554"));
    driver.findElement(By.cssSelector("li:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector("li:nth-child(1) > span")).getText(), is("BreezoMeter AQI"));
    driver.findElement(By.cssSelector("h4:nth-child(3)")).click();
    assertThat(driver.findElement(By.cssSelector("h4:nth-child(3)")).getText(), containsString("Health Recommendations:"));
    driver.findElement(By.cssSelector("h3")).click();
    assertThat(driver.findElement(By.cssSelector("h3")).getText(), is("Pollutants and concentrations"));
  }
}
